# Generated by Django 4.1.1 on 2022-09-21 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_alter_product_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cart',
        ),
    ]
