# Generated by Django 4.1.1 on 2022-09-09 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WishList',
        ),
    ]
