# Generated by Django 4.1.1 on 2022-09-09 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_cart_alter_product_id'),
        ('customer', '0002_delete_wishlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='cart',
            field=models.ManyToManyField(related_name='customer_cart', to='store.product'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='wish_list',
            field=models.ManyToManyField(related_name='customer_whish_list', to='store.product'),
        ),
    ]
