# Generated by Django 4.1.1 on 2022-09-10 08:58

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_customer_cart_alter_customer_wish_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
