# Generated by Django 4.1.1 on 2022-09-21 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0006_order_orderdetails_remove_customer_purchase_history_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='customer_id',
            new_name='customer',
        ),
    ]
