# Generated by Django 4.1.1 on 2022-09-23 16:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0007_rename_customer_id_order_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdetails',
            name='deliverd_at',
            field=models.DateField(default=datetime.datetime(2022, 9, 23, 16, 18, 56, 106111)),
        ),
    ]
