# Generated by Django 4.1.1 on 2022-09-23 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0009_alter_orderdetails_deliverd_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdetails',
            name='deliverd_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
