# Generated by Django 4.1.1 on 2022-09-23 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0010_alter_orderdetails_deliverd_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='orders',
            field=models.ManyToManyField(related_name='customer_orders', to='customer.order'),
        ),
    ]
